import { Inter } from 'next/font/google';

import './globals.css';
import { cn } from 'lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    </head>
    <body className={cn('flex flex-col min-h-screen', inter.className)}>{children}</body>
  </html>
);

export default RootLayout;
