name: Code check

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Eslint, Typescript, prettier and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: ESLint
        run: npm run lint
